DECLARE V_SET_NAME VARCHAR2(30);
BEGIN SELECT SET_NAME INTO V_SET_NAME FROM CHANGE_SETS
WHERE PUBLISHER=(SELECT USER FROM DUAL); 
DBMS_CDC_PUBLISH.ALTER_CHANGE_SET( 
CHANGE_SET_NAME => V_SET_NAME, ENABLE_CAPTURE => 'Y'); END; 
/

